### ISSUE TITLE
Test demo scenarios

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8-kui#16]
Both scenarios below are going to run on Istio 1.4.6

### Initial set up (regular shell)
1. Deploy book info with baseline: reviews-v2 and show the application in the browser
2. Start load generator

### Apply scenario 1 set up (KUI shell)
3. Deploy Candidate: reviews-v3

### Create experiment in experiment creation tab (KUI side car)
4. Criterion: iter8_latency with an absolute threshold (0.2 sec)

### Conduct experiment (KUI side car / shell)
5. Get recommendation in decision tab
6. Play with sliders
7. Apply latest traffic split and show the application in the browser to verify traffic split
8. Also verify traffic split by looking into virtual service / destination rule (KUI shell)
... after a while ... 
9.  Get recommendation in decision tab
10. Play with sliders
11. Apply latest traffic split and show the application in the browser to verify traffic split
12. Verify traffic split by looking into virtual service / destination rule (KUI shell)
... after a while ... 
13. Get recommendation in decision tab

### Apply scenario 2 set up (KUI shell)
0. Baseline: reviews-v3 (already running from scenario 1). v2 is also deployed with 0 traffic
1. Deploy Candidates: reviews-v4, v5, v6 (v6 = v3) (v4 will fail latency constraint) (v5 will have errors)

### Create experiment in experiment creation tab (KUI side car)
2. Criterion: iter8_latency with an absolute threshold (0.2 sec)
3. Criterion: iter8_error_rate used as a reward (no thresholds)

### Conduct experiment (KUI side car / shell)
4. Get recommendation in decision tab
5. Play with sliders
6. Apply latest traffic split and show the application in the browser to verify traffic split
7. Verify traffic split by looking into virtual service / destination rule (KUI shell)
... after a while ... 
8.  Get recommendation in decision tab
9. Play with sliders
10. Apply latest traffic split and show the application in the browser to verify traffic split
11. Verify traffic split by looking into virtual service / destination rule (KUI shell)
... after a while ... 
12. Get recommendation in decision tab

**Comment by avhhh** [comment]
Are we using the iter8_total_latency or iter8_mean_latency for the threshold criteria?

**Comment by sriumcp** [comment]
`iter8_mean_latency`
